### ISSUE TITLE
Statamic V4 Support

### ISSUE THREAD

**Issue by heywhy** [riasvdv/statamic-markdown-highlight#11]
I'm unable to upgrade to v4 because of the requirement in the `composer.json` file.

<img width="1439" alt="Screenshot 2023-05-16 at 14 13 01" src="https://github.com/riasvdv/statamic-markdown-highlight/assets/13123868/b0248b96-3b8c-47e2-a019-7d81dfc2d89b">

**Comment by riasvdv** [comment]
I've tagged a new release which should work!
