### ISSUE TITLE
Error after update to 1.0.3 and Statamic 3.0.0-beta.46

### ISSUE THREAD

**Issue by jmartsch** [riasvdv/statamic-markdown-highlight#4]
This is the error I get: `Object of class Rias\MarkdownHighlight\Tags\Highlight could not be converted to string`

Here is the log and a screenshot of my stacktrace (I was not able to share it via flare):

![dotnetic-statamic localhost_](https://user-images.githubusercontent.com/551551/90611802-7ee7f280-e207-11ea-91f1-60f5cc81a15f.png)

[laravel.log](https://github.com/riasvdv/statamic-markdown-highlight/files/5095089/laravel.log)

**Comment by riasvdv** [comment]
Thanks, should be fixed in 1.0.4!

**Comment by jmartsch** [comment]
Thanks. It works now 👍
