### ISSUE TITLE
Doesn’t seem to inherit Markdown behaviours

### ISSUE THREAD

**Issue by mikerockett** [riasvdv/statamic-markdown-highlight#5]
When switching from `markdown` to `markdown_highlight`, other options such as `smartypants` don’t seem to take effect.

Is this the intended behaviour? I'm pretty new to Statamic, so not entirely sure how to go about fixing it.

Thanks!

**Comment by riasvdv** [comment]
You shouldn't need those options when highlighting code. This is intended behaviour, you should use the default markdown fieldtype for normal text

**Comment by mikerockett** [comment]
I see, but what about mixing normal markdown content with highlighted code? More often that not, people will want to include highlighted code in a blog post or something that uses a simple markdown content field (as opposed to using Bard).

**Comment by riasvdv** [comment]
Then I'd accept a PR that implements this. Personally I find a Bard field easier.

**Comment by mikerockett** [comment]
Thanks, I've gone ahead and opened up a PR (https://github.com/riasvdv/statamic-markdown-highlight/pull/6) that implements this. From my side, it's more important to get the 'expected' behaviour in, given that the configuration items from the core field type are exposed, but never used.
