### ISSUE TITLE
spatie/commonmark-shiki-highlighter blocking Laravle 9 upgrade

### ISSUE THREAD

**Issue by rickmills** [riasvdv/statamic-markdown-highlight#8]
Hi there,

Just wanted to report a slight issue. The package uses `spatie/commonmark-shiki-highlighter` 1.x, which requires an earlier`leage/commonmark` version than Laravel. 

Spatie look to have released version 2 of their package to add Laravel 9 support, but right now this package is unable to move beyond Laravel 8.

**Comment by heywhy** [comment]
It's a blocker for me too. 😓

**Comment by riasvdv** [comment]
Feel free to send a PR with the necessary updates, otherwise I’ll try to work on this as soon as  I update my own site

**Comment by heywhy** [comment]
@riasvdv I've created PR #9 to handle this issue and I also confirmed that it works as expected. I'm looking forward to a new release.

**Comment by riasvdv** [comment]
Should be fixed in 2.0.1!
